import React, { useState, useMemo } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, CheckCircle2, AlertTriangle, Users, Shield, Star, Sparkles, RefreshCw, Filter, Search } from 'lucide-react';
import { fmtCr, LEAGUE_DEFAULTS } from '../utils/playerUtils';

const CustomLineupModal = ({
    isOpen,
    onClose,
    team,
    roomCode,
    league = 'ipl',
    currency = 'inr',
    allPlayersMap = {},
    onEvaluationUpdated
}) => {
    if (!isOpen || !team) return null;

    const squad = team.playersAcquired || [];
    const fmt = (lakhs) => fmtCr(lakhs, currency, LEAGUE_DEFAULTS[league] || 'inr');

    // Helper to get consistent player name from any shape
    const getCleanName = (p) => {
        if (!p) return '';
        if (typeof p === 'string') return p.trim();
        return (p.name || p.player?.name || p.player || '').toString().trim();
    };

    // ─── Extract AI's original selections ───
    const aiStartingXI = useMemo(() => {
        // Priority 1: Check team.evaluation.playing_xi (names or objects generated by AI)
        if (Array.isArray(team.evaluation?.playing_xi) && team.evaluation.playing_xi.length > 0) {
            const names = team.evaluation.playing_xi.map(getCleanName).filter(Boolean);
            // Verify names exist in squad
            const validNames = names.filter(n => squad.some(sp => getCleanName(sp).toLowerCase() === n.toLowerCase()));
            if (validNames.length === 11) return validNames;
        }

        // Priority 2: Check team.playing11 (ObjectIds or strings)
        if (Array.isArray(team.playing11) && team.playing11.length === 11) {
            const mapped = team.playing11.map(item => {
                const idStr = String(item?._id || item);
                const found = squad.find(sp => {
                    const spId = String(sp._id || '');
                    const spPlayerId = String(sp.player?._id || sp.player || '');
                    return spId === idStr || spPlayerId === idStr || getCleanName(sp).toLowerCase() === idStr.toLowerCase();
                });
                return found ? getCleanName(found) : null;
            }).filter(Boolean);
            if (mapped.length === 11) return mapped;
        }

        // Priority 3: Fallback to first 11 squad players
        return squad.slice(0, 11).map(getCleanName);
    }, [team, squad]);

    const aiBench = useMemo(() => {
        // Priority 1: Check team.evaluation.substitutes
        if (Array.isArray(team.evaluation?.substitutes) && team.evaluation.substitutes.length > 0) {
            const names = team.evaluation.substitutes.map(getCleanName).filter(Boolean);
            const validNames = names.filter(n => squad.some(sp => getCleanName(sp).toLowerCase() === n.toLowerCase()));
            if (validNames.length > 0) return validNames.slice(0, 8);
        }

        // Priority 2: Check team.impactPlayers
        if (Array.isArray(team.impactPlayers) && team.impactPlayers.length > 0) {
            const mapped = team.impactPlayers.map(item => {
                const idStr = String(item?._id || item);
                const found = squad.find(sp => {
                    const spId = String(sp._id || '');
                    const spPlayerId = String(sp.player?._id || sp.player || '');
                    return spId === idStr || spPlayerId === idStr || getCleanName(sp).toLowerCase() === idStr.toLowerCase();
                });
                return found ? getCleanName(found) : null;
            }).filter(Boolean);
            if (mapped.length > 0) return mapped.slice(0, 8);
        }

        // Priority 3: Remaining squad players not in AI XI (up to 8)
        return squad
            .map(getCleanName)
            .filter(n => !aiStartingXI.some(aiName => aiName.toLowerCase() === n.toLowerCase()))
            .slice(0, 8);
    }, [team, squad, aiStartingXI]);

    // Initial state set directly to AI's selection
    const [playingXI, setPlayingXI] = useState(() => aiStartingXI);

    const [benchReserves, setBenchReserves] = useState(() => {
        const initial = [...aiBench];
        // Ensure up to 8 reserves are filled so total is up to 19
        for (const sp of squad) {
            const name = getCleanName(sp);
            const inXI = aiStartingXI.some(x => x.toLowerCase() === name.toLowerCase());
            const inBench = initial.some(b => b.toLowerCase() === name.toLowerCase());
            if (!inXI && !inBench && initial.length < 8 && (aiStartingXI.length + initial.length < 19)) {
                initial.push(name);
            }
        }
        return initial.slice(0, 8);
    });

    const [filterRole, setFilterRole] = useState('ALL');
    const [searchQuery, setSearchQuery] = useState('');
    const [isSubmitting, setIsSubmitting] = useState(false);
    const [errorMsg, setErrorMsg] = useState(null);

    // Helpers to inspect player properties
    const getPlayerInfo = (p) => {
        const pName = getCleanName(p);
        const pIdStr = String(p._id || p.player?._id || p.player || '');
        const cached = allPlayersMap[pIdStr] || allPlayersMap[p.player] || {};
        const role = p.role || p.player?.role || cached.role || 'Player';
        const isOverseas = Boolean(p.isOverseas ?? p.player?.isOverseas ?? cached.isOverseas);
        const img = p.image_path || p.photoUrl || p.imagepath || p.player?.image_path || cached.image_path || cached.photoUrl || '';
        return { name: pName, role, isOverseas, img, price: p.boughtFor || p.points || 0 };
    };

    // Validation checks
    const xiPlayersInfo = useMemo(() => {
        return playingXI.map(name => {
            const p = squad.find(sp => getCleanName(sp).toLowerCase() === name.toLowerCase());
            return p ? getPlayerInfo(p) : { name, role: '', isOverseas: false };
        });
    }, [playingXI, squad]);

    const overseasInXI = xiPlayersInfo.filter(p => p.isOverseas).length;
    const maxOverseasAllowed = 4;

    const wkInXI = xiPlayersInfo.filter(p => {
        const r = String(p.role || '').toLowerCase();
        return r.includes('keeper') || r.includes('wk');
    }).length;

    const totalSelected = playingXI.length + benchReserves.length;
    const isXiCountValid = playingXI.length === 11;
    const isTotalValid = totalSelected <= 19;
    const isOverseasValid = overseasInXI <= maxOverseasAllowed;
    const isWkValid = wkInXI >= 1;

    const canSubmit = isXiCountValid && isTotalValid && isOverseasValid && isWkValid && !isSubmitting;

    // Toggle player status
    const toggleStartingXI = (playerName) => {
        setErrorMsg(null);
        if (playingXI.includes(playerName)) {
            setPlayingXI(prev => prev.filter(n => n !== playerName));
        } else {
            if (playingXI.length >= 11) {
                setErrorMsg('Starting Playing XI is already full (11 players). Remove a player first.');
                return;
            }
            setBenchReserves(prev => prev.filter(n => n !== playerName));
            setPlayingXI(prev => [...prev, playerName]);
        }
    };

    const toggleBenchReserve = (playerName) => {
        setErrorMsg(null);
        if (benchReserves.includes(playerName)) {
            setBenchReserves(prev => prev.filter(n => n !== playerName));
        } else {
            if (benchReserves.length >= 8) {
                setErrorMsg('Bench reserves are at max capacity (8 players). Total evaluated cannot exceed 19 players.');
                return;
            }
            if (playingXI.length + benchReserves.length >= 19) {
                setErrorMsg('Maximum 19 players total (11 starters + up to 8 reserves) can be evaluated.');
                return;
            }
            setPlayingXI(prev => prev.filter(n => n !== playerName));
            setBenchReserves(prev => [...prev, playerName]);
        }
    };

    // Restore to AI selection
    const handleRestoreAIDefault = () => {
        setPlayingXI([...aiStartingXI]);
        const initialBench = [...aiBench];
        for (const sp of squad) {
            const name = getCleanName(sp);
            const inXI = aiStartingXI.some(x => x.toLowerCase() === name.toLowerCase());
            const inBench = initialBench.some(b => b.toLowerCase() === name.toLowerCase());
            if (!inXI && !inBench && initialBench.length < 8 && (aiStartingXI.length + initialBench.length < 19)) {
                initialBench.push(name);
            }
        }
        setBenchReserves(initialBench.slice(0, 8));
        setErrorMsg(null);
    };

    // Submit custom evaluation
    const handleSubmit = async () => {
        if (!canSubmit) return;
        setIsSubmitting(true);
        setErrorMsg(null);

        try {
            const apiUrl = import.meta.env.VITE_API_URL || '';
            const res = await fetch(`${apiUrl}/api/room/${roomCode}/custom-evaluate`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    teamName: team.teamName,
                    playingXI,
                    benchReserves
                })
            });

            let data;
            try {
                const text = await res.text();
                data = JSON.parse(text);
            } catch (pErr) {
                throw new Error(`Server returned unexpected response (${res.status}). Please verify the server is running and retry.`);
            }

            if (!res.ok || !data.success) {
                throw new Error(data.error || 'Failed to submit custom lineup.');
            }

            if (data.success && onEvaluationUpdated) {
                onEvaluationUpdated(data.team, data.teams);
            }
            onClose();
        } catch (err) {
            console.error('Custom lineup error:', err);
            setErrorMsg(err.message || 'Error communicating with AI evaluator.');
            setIsSubmitting(false);
        }
    };

    // Filtered Squad
    const filteredSquad = squad.filter(p => {
        const pInfo = getPlayerInfo(p);
        const matchesSearch = pInfo.name.toLowerCase().includes(searchQuery.toLowerCase());
        if (!matchesSearch) return false;

        if (filterRole === 'ALL') return true;
        if (filterRole === 'AI_XI') return aiStartingXI.some(n => n.toLowerCase() === pInfo.name.toLowerCase());
        if (filterRole === 'AI_BENCH') return aiBench.some(n => n.toLowerCase() === pInfo.name.toLowerCase());
        const r = pInfo.role.toLowerCase();
        if (filterRole === 'BATTER') return r.includes('bat');
        if (filterRole === 'BOWLER') return r.includes('bowl') && !r.includes('all');
        if (filterRole === 'ALLROUNDER') return r.includes('all');
        if (filterRole === 'WK') return r.includes('keeper') || r.includes('wk');
        return true;
    });

    return (
        <AnimatePresence>
            <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-6 bg-black/85 backdrop-blur-md overflow-y-auto">
                <motion.div
                    initial={{ opacity: 0, scale: 0.95, y: 20 }}
                    animate={{ opacity: 1, scale: 1, y: 0 }}
                    exit={{ opacity: 0, scale: 0.95, y: 20 }}
                    transition={{ duration: 0.25, ease: 'easeOut' }}
                    className="relative w-full max-w-5xl bg-slate-950/95 border border-white/10 rounded-[32px] shadow-[0_25px_80px_rgba(0,0,0,0.85)] overflow-hidden flex flex-col max-h-[92vh]"
                >
                    {/* Top gradient highlight */}
                    <div className="absolute top-0 inset-x-0 h-1 bg-gradient-to-r from-amber-500 via-purple-500 to-blue-500" />

                    {/* ─── MODAL HEADER ─── */}
                    <div className="p-5 sm:p-6 border-b border-white/8 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
                        <div className="flex items-center gap-3">
                            <div className="w-12 h-12 rounded-2xl bg-amber-500/10 border border-amber-500/30 flex items-center justify-center text-amber-400 shrink-0">
                                <Sparkles className="w-6 h-6" />
                            </div>
                            <div>
                                <div className="flex items-center gap-2">
                                    <h3 className="text-xl sm:text-2xl font-black uppercase tracking-tight text-white">
                                        Customize Playing XI & Bench
                                    </h3>
                                    <span className="px-2.5 py-0.5 rounded-full text-[10px] font-black uppercase tracking-wider bg-amber-500/20 text-amber-300 border border-amber-500/30">
                                        {team.teamName}
                                    </span>
                                </div>
                                <p className="text-xs text-slate-400 font-medium mt-1">
                                    Choose your starting 11 and up to 8 bench reserves (max 19 players total) from your {squad.length}-man roster to challenge the AI verdict.
                                </p>
                            </div>
                        </div>

                        <div className="flex items-center gap-2 self-end sm:self-auto">
                            <button
                                onClick={handleRestoreAIDefault}
                                className="px-3 py-1.5 rounded-xl border border-cyan-500/30 bg-cyan-500/10 hover:bg-cyan-500/20 text-cyan-300 text-[10px] font-black uppercase tracking-wider transition-all flex items-center gap-1.5 shadow-[0_0_15px_rgba(6,182,212,0.15)]"
                                title="Reset to what AI originally selected"
                            >
                                <RefreshCw className="w-3.5 h-3.5 text-cyan-400" />
                                Restore AI Default
                            </button>
                            <button
                                onClick={onClose}
                                className="w-9 h-9 rounded-xl bg-white/5 hover:bg-white/10 border border-white/10 flex items-center justify-center text-slate-400 hover:text-white transition-all"
                            >
                                <X className="w-5 h-5" />
                            </button>
                        </div>
                    </div>

                    {/* ─── AI SELECTION SUMMARY CALLOUT BANNER ─── */}
                    <div className="px-5 sm:px-6 py-2.5 bg-gradient-to-r from-cyan-950/40 via-blue-950/30 to-purple-950/40 border-b border-white/8 flex items-center justify-between gap-3 text-xs">
                        <div className="flex items-center gap-2 text-slate-300">
                            <span className="w-2 h-2 rounded-full bg-cyan-400 animate-pulse" />
                            <span className="text-[11px] font-medium">
                                <strong className="text-cyan-300 font-bold">AI Lineup Transparency:</strong> The badges below show exactly who the AI originally selected as <span className="text-cyan-300 font-bold">🤖 Starting XI</span> and <span className="text-purple-300 font-bold">🛡️ Bench Reserves</span>.
                            </span>
                        </div>
                        <div className="hidden sm:flex items-center gap-2 text-[10px] font-mono text-slate-400">
                            <span>AI Starters: {aiStartingXI.length}</span>
                            <span>·</span>
                            <span>AI Bench: {aiBench.length}</span>
                        </div>
                    </div>

                    {/* ─── STATS & VALIDATION BAR ─── */}
                    <div className="px-5 sm:px-6 py-3.5 bg-white/[0.02] border-b border-white/8 grid grid-cols-2 sm:grid-cols-5 gap-2 sm:gap-3 text-xs">
                        {/* Playing XI count */}
                        <div className={`p-2.5 rounded-xl border flex flex-col items-center justify-center transition-colors ${isXiCountValid ? 'bg-blue-500/10 border-blue-500/30 text-blue-300' : 'bg-rose-500/10 border-rose-500/30 text-rose-300'}`}>
                            <span className="text-[8px] font-black uppercase tracking-widest opacity-70">Playing XI (Must be 11)</span>
                            <span className="text-base font-black font-mono">{playingXI.length} / 11</span>
                        </div>

                        {/* Bench reserves count */}
                        <div className="p-2.5 rounded-xl border bg-purple-500/10 border-purple-500/30 text-purple-300 flex flex-col items-center justify-center">
                            <span className="text-[8px] font-black uppercase tracking-widest opacity-70">Bench Reserves (Max 8)</span>
                            <span className="text-base font-black font-mono">{benchReserves.length} / 8</span>
                        </div>

                        {/* Total players selected */}
                        <div className={`p-2.5 rounded-xl border flex flex-col items-center justify-center ${isTotalValid ? 'bg-emerald-500/10 border-emerald-500/30 text-emerald-300' : 'bg-rose-500/10 border-rose-500/30 text-rose-300'}`}>
                            <span className="text-[8px] font-black uppercase tracking-widest opacity-70">Total Selected (Max 19)</span>
                            <span className="text-base font-black font-mono">{totalSelected} / 19</span>
                        </div>

                        {/* Overseas in XI */}
                        <div className={`p-2.5 rounded-xl border flex flex-col items-center justify-center ${isOverseasValid ? 'bg-amber-500/10 border-amber-500/30 text-amber-300' : 'bg-rose-500/10 border-rose-500/30 text-rose-300'}`}>
                            <span className="text-[8px] font-black uppercase tracking-widest opacity-70">Overseas in XI (Max 4)</span>
                            <span className="text-base font-black font-mono">{overseasInXI} / 4</span>
                        </div>

                        {/* WKs in XI */}
                        <div className={`col-span-2 sm:col-span-1 p-2.5 rounded-xl border flex flex-col items-center justify-center ${isWkValid ? 'bg-sky-500/10 border-sky-500/30 text-sky-300' : 'bg-rose-500/10 border-rose-500/30 text-rose-300'}`}>
                            <span className="text-[8px] font-black uppercase tracking-widest opacity-70">Keeper in XI (Min 1)</span>
                            <span className="text-base font-black font-mono">{wkInXI} / 1</span>
                        </div>
                    </div>

                    {/* ─── FILTERS & SEARCH ─── */}
                    <div className="px-5 sm:px-6 py-3 border-b border-white/5 flex flex-wrap items-center justify-between gap-3">
                        <div className="flex flex-wrap items-center gap-1.5">
                            {[
                                { id: 'ALL', label: `All (${squad.length})` },
                                { id: 'AI_XI', label: `🤖 AI XI (${aiStartingXI.length})` },
                                { id: 'AI_BENCH', label: `🛡️ AI Bench (${aiBench.length})` },
                                { id: 'BATTER', label: 'Batters' },
                                { id: 'BOWLER', label: 'Bowlers' },
                                { id: 'ALLROUNDER', label: 'All-Rounders' },
                                { id: 'WK', label: 'WKs' }
                            ].map(tab => (
                                <button
                                    key={tab.id}
                                    onClick={() => setFilterRole(tab.id)}
                                    className={`px-3 py-1 rounded-xl text-[9px] font-black uppercase tracking-wider transition-all ${filterRole === tab.id ? 'bg-white/20 text-white border border-white/30' : 'bg-white/5 text-slate-400 border border-white/5 hover:bg-white/10'}`}
                                >
                                    {tab.label}
                                </button>
                            ))}
                        </div>

                        <div className="relative min-w-[200px]">
                            <Search className="w-3.5 h-3.5 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2" />
                            <input
                                type="text"
                                value={searchQuery}
                                onChange={(e) => setSearchQuery(e.target.value)}
                                placeholder="Search squad player..."
                                className="w-full bg-white/5 border border-white/10 rounded-xl pl-8 pr-3 py-1.5 text-xs text-white placeholder-slate-500 focus:outline-none focus:border-amber-400/50"
                            />
                        </div>
                    </div>

                    {/* ─── ERROR BANNER (IF ANY) ─── */}
                    {errorMsg && (
                        <div className="mx-5 sm:mx-6 mt-3 p-3 rounded-2xl border border-rose-500/40 bg-rose-500/10 text-rose-300 text-xs font-bold flex items-center gap-2">
                            <AlertTriangle className="w-4 h-4 shrink-0 text-rose-400" />
                            <span>{errorMsg}</span>
                        </div>
                    )}

                    {/* ─── SQUAD SELECTION GRID ─── */}
                    <div className="p-5 sm:p-6 overflow-y-auto flex-1 space-y-3">
                        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
                            {filteredSquad.map((player, idx) => {
                                const info = getPlayerInfo(player);
                                const isStarter = playingXI.includes(info.name);
                                const isReserve = benchReserves.includes(info.name);
                                const wasAiStarter = aiStartingXI.some(n => n.toLowerCase() === info.name.toLowerCase());
                                const wasAiReserve = aiBench.some(n => n.toLowerCase() === info.name.toLowerCase());

                                return (
                                    <div
                                        key={player._id || player.player || idx}
                                        className={`
                                            relative rounded-2xl p-3.5 border transition-all duration-200 flex flex-col justify-between gap-3 group
                                            ${isStarter
                                                ? 'bg-blue-500/10 border-blue-500/40 shadow-[0_0_20px_rgba(59,130,246,0.15)]'
                                                : isReserve
                                                    ? 'bg-purple-500/10 border-purple-500/40 shadow-[0_0_20px_rgba(168,85,247,0.15)]'
                                                    : 'bg-white/[0.02] border-white/6 hover:bg-white/[0.05] hover:border-white/10 opacity-70 hover:opacity-100'
                                            }
                                        `}
                                    >
                                        <div>
                                            {/* AI Original Status Pill */}
                                            <div className="mb-2 flex items-center gap-1.5">
                                                {wasAiStarter && (
                                                    <span className="px-2 py-0.5 rounded-full text-[9px] font-black uppercase tracking-wider bg-cyan-500/20 text-cyan-300 border border-cyan-500/40 shadow-[0_0_10px_rgba(6,182,212,0.2)] flex items-center gap-1">
                                                        🤖 AI Playing XI
                                                    </span>
                                                )}
                                                {wasAiReserve && (
                                                    <span className="px-2 py-0.5 rounded-full text-[9px] font-black uppercase tracking-wider bg-purple-500/20 text-purple-300 border border-purple-500/40 shadow-[0_0_10px_rgba(168,85,247,0.2)] flex items-center gap-1">
                                                        🛡️ AI Bench
                                                    </span>
                                                )}
                                                {!wasAiStarter && !wasAiReserve && (
                                                    <span className="px-2 py-0.5 rounded-full text-[9px] font-black uppercase tracking-wider bg-white/5 text-slate-400 border border-white/10 flex items-center gap-1">
                                                        🚫 AI Excluded
                                                    </span>
                                                )}
                                            </div>

                                            <div className="flex items-center gap-3">
                                                {/* Avatar */}
                                                <div className="relative w-11 h-11 rounded-xl bg-slate-800 border border-white/10 overflow-hidden shrink-0 flex items-center justify-center">
                                                    {info.img ? (
                                                        <img
                                                            src={info.img}
                                                            alt={info.name}
                                                            className="w-full h-full object-cover object-top"
                                                            onError={(e) => {
                                                                e.target.onerror = null;
                                                                e.target.src = `https://api.dicebear.com/7.x/initials/svg?seed=${encodeURIComponent(info.name)}`;
                                                            }}
                                                        />
                                                    ) : (
                                                        <span className="text-xs font-black text-slate-400">{info.name.slice(0, 2).toUpperCase()}</span>
                                                    )}
                                                    {info.isOverseas && (
                                                        <span className="absolute bottom-0 right-0 bg-blue-600 text-[7px] font-black px-1 rounded-tl text-white">
                                                            ✈️
                                                        </span>
                                                    )}
                                                </div>

                                                {/* Details */}
                                                <div className="min-w-0 flex-1">
                                                    <div className="flex items-center gap-1.5 truncate">
                                                        <span className="text-sm font-black text-white truncate">{info.name}</span>
                                                    </div>
                                                    <div className="flex items-center gap-2 mt-0.5">
                                                        <span className="text-[9px] font-bold text-slate-400 uppercase tracking-wider">{info.role}</span>
                                                        <span className="text-[9px] font-mono font-bold text-amber-400">{fmt(info.price)}</span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        {/* Status badge & toggles */}
                                        <div className="flex items-center justify-between gap-2 pt-2 border-t border-white/5">
                                            <div>
                                                {isStarter && (
                                                    <span className="px-2 py-0.5 rounded-md text-[8px] font-black uppercase tracking-widest bg-blue-500/20 text-blue-300 border border-blue-500/30 flex items-center gap-1">
                                                        <Star className="w-2.5 h-2.5" /> In Starters
                                                    </span>
                                                )}
                                                {isReserve && (
                                                    <span className="px-2 py-0.5 rounded-md text-[8px] font-black uppercase tracking-widest bg-purple-500/20 text-purple-300 border border-purple-500/30 flex items-center gap-1">
                                                        <Shield className="w-2.5 h-2.5" /> In Reserves
                                                    </span>
                                                )}
                                                {!isStarter && !isReserve && (
                                                    <span className="text-[8px] font-bold text-slate-500 uppercase tracking-widest">
                                                        Excluded
                                                    </span>
                                                )}
                                            </div>

                                            <div className="flex items-center gap-1.5">
                                                <button
                                                    type="button"
                                                    onClick={() => toggleStartingXI(info.name)}
                                                    className={`px-2.5 py-1 rounded-lg text-[9px] font-black uppercase tracking-wider transition-all ${isStarter ? 'bg-blue-600 text-white shadow-sm' : 'bg-white/5 hover:bg-blue-500/20 text-slate-300 hover:text-blue-300 border border-white/10'}`}
                                                >
                                                    {isStarter ? 'In XI ✓' : '+ XI'}
                                                </button>
                                                <button
                                                    type="button"
                                                    onClick={() => toggleBenchReserve(info.name)}
                                                    className={`px-2.5 py-1 rounded-lg text-[9px] font-black uppercase tracking-wider transition-all ${isReserve ? 'bg-purple-600 text-white shadow-sm' : 'bg-white/5 hover:bg-purple-500/20 text-slate-300 hover:text-purple-300 border border-white/10'}`}
                                                >
                                                    {isReserve ? 'Bench ✓' : '+ Bench'}
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                );
                            })}
                        </div>
                    </div>

                    {/* ─── MODAL FOOTER ─── */}
                    <div className="p-5 sm:p-6 border-t border-white/8 bg-slate-950 flex flex-col sm:flex-row items-center justify-between gap-4">
                        <div className="text-xs text-slate-400 flex flex-col gap-0.5 text-center sm:text-left">
                            {!isXiCountValid && (
                                <span className="text-rose-400 font-bold">⚠️ Starting Playing XI must have exactly 11 players (currently {playingXI.length}).</span>
                            )}
                            {!isOverseasValid && (
                                <span className="text-rose-400 font-bold">⚠️ Playing XI cannot exceed {maxOverseasAllowed} overseas players (currently {overseasInXI}).</span>
                            )}
                            {!isWkValid && (
                                <span className="text-rose-400 font-bold">⚠️ Starting Playing XI requires at least 1 wicketkeeper.</span>
                            )}
                            {!isTotalValid && (
                                <span className="text-rose-400 font-bold">⚠️ Total evaluated players cannot exceed 19 (currently {totalSelected}).</span>
                            )}
                            {isXiCountValid && isOverseasValid && isWkValid && isTotalValid && (
                                <span className="text-emerald-400 font-bold flex items-center gap-1.5 justify-center sm:justify-start">
                                    <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                                    Lineup ready for tactical AI review ({playingXI.length} Starters + {benchReserves.length} Reserves)!
                                </span>
                            )}
                        </div>

                        <div className="flex items-center gap-3 w-full sm:w-auto">
                            <button
                                onClick={onClose}
                                disabled={isSubmitting}
                                className="flex-1 sm:flex-none px-5 py-2.5 rounded-xl border border-white/10 bg-white/5 hover:bg-white/10 text-slate-300 text-xs font-black uppercase tracking-wider transition-all"
                            >
                                Cancel
                            </button>
                            <button
                                onClick={handleSubmit}
                                disabled={!canSubmit}
                                className={`
                                    flex-1 sm:flex-none px-6 py-2.5 rounded-xl text-xs font-black uppercase tracking-wider transition-all flex items-center justify-center gap-2
                                    ${canSubmit
                                        ? 'bg-gradient-to-r from-amber-500 via-orange-500 to-amber-600 hover:from-amber-400 hover:to-orange-500 text-black shadow-[0_0_30px_rgba(245,158,11,0.3)] hover:scale-[1.02] cursor-pointer'
                                        : 'bg-white/10 text-slate-500 border border-white/5 cursor-not-allowed'
                                    }
                                `}
                            >
                                {isSubmitting ? (
                                    <>
                                        <RefreshCw className="w-4 h-4 animate-spin text-black" />
                                        <span>AI Re-Evaluating...</span>
                                    </>
                                ) : (
                                    <>
                                        <Sparkles className="w-4 h-4" />
                                        <span>Submit Custom Lineup</span>
                                    </>
                                )}
                            </button>
                        </div>
                    </div>
                </motion.div>
            </div>
        </AnimatePresence>
    );
};

export default CustomLineupModal;
